# Generated by Django 5.2.12 on 2026-04-05 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('time', models.TimeField(auto_now_add=True)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
