# Generated by Django 5.2.12 on 2026-04-05 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='active',
            new_name='is_completed',
        ),
    ]
