# Generated by Django 5.2.12 on 2026-04-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_rename_active_jobs_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='time',
            field=models.TimeField(),
        ),
    ]
