# Generated by Django 5.2.12 on 2026-04-08 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_alter_jobs_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='created',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
