# Generated by Django 5.2.12 on 2026-04-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0006_alter_jobs_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='created',
            field=models.TimeField(),
        ),
    ]
