# Generated by Django 5.2 on 2026-04-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0007_alter_jobs_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='created',
            field=models.TimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
